# Generated by Django 4.1.1 on 2022-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
