# Generated by Django 4.1.1 on 2022-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_competition_description_contest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
