# Generated by Django 4.1.1 on 2022-11-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_competition_is_active_contest_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_active',
        ),
        migrations.AddField(
            model_name='competition',
            name='result_comment',
            field=models.TextField(default='', help_text='Comment to the final results'),
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Running'), ('NEW', 'In preparation'), ('CLOSED', 'In evaluation'), ('OLD', 'Over')], default='NEW', max_length=6),
        ),
        migrations.AddField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(help_text='Winning team of the competition', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contest.team'),
        ),
        migrations.AddField(
            model_name='competition',
            name='winner_points',
            field=models.FloatField(help_text='Assignmend by judge', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Running'), ('NEW', 'In preparation'), ('CLOSED', 'In evaluation'), ('OLD', 'Over')], default='NEW', max_length=6),
        ),
        migrations.AlterField(
            model_name='competition',
            name='contest',
            field=models.ForeignKey(help_text='Competition is one part of contest.', on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(default='Rules of the competition and description of the task,'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(help_text='Name of the competition.', max_length=200),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(help_text='There can be more participants in a competition', to='contest.team'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='runs',
            field=models.ManyToManyField(help_text='Competition has more runs from different teams.', related_name='runs', through='contest.Run', to='contest.team'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(default='', help_text='Further description of the contest, such as time and place'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(help_text='Name of the contest. ', max_length=200),
        ),
        migrations.AlterField(
            model_name='run',
            name='competition',
            field=models.ForeignKey(help_text='source competition', on_delete=django.db.models.deletion.CASCADE, to='contest.competition'),
        ),
        migrations.AlterField(
            model_name='run',
            name='judge_comment',
            field=models.CharField(blank=True, help_text='Comment by a Judge', max_length=200),
        ),
        migrations.AlterField(
            model_name='run',
            name='score',
            field=models.FloatField(help_text='Assigned by a Judge'),
        ),
        migrations.AlterField(
            model_name='run',
            name='team',
            field=models.ForeignKey(help_text='Who performed the run', on_delete=django.db.models.deletion.CASCADE, to='contest.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contest',
            field=models.ForeignKey(help_text='a team belongs to a contest', on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(default='', help_text='Team members and affiliation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Identifier of the team', max_length=200),
        ),
    ]
