# Generated by Django 4.1.1 on 2022-11-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_remove_competition_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Team members and affiliation'),
        ),
    ]
