# Generated by Django 4.1.1 on 2022-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_alter_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Rules of the competition and description of the task,'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Further description of the contest, such as time and place'),
        ),
    ]
