# Generated by Django 4.1.1 on 2022-11-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_alter_competition_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winning team of the competition', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contest.team'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='winner_points',
            field=models.FloatField(blank=True, help_text='Assignmend by judge', null=True),
        ),
    ]
