# Generated by Django 4.1.1 on 2022-11-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_alter_competition_result_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rules',
            field=models.TextField(blank=True, default='', help_text='Further description of the contest, such as rules and conditions'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short description of the contest, such as time and place'),
        ),
    ]
