# Generated by Django 4.1.1 on 2022-11-05 16:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_contest_rules_alter_contest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Further description of the contest, such as rules and conditions'),
        ),
    ]
