# Generated by Django 4.1.1 on 2022-11-05 16:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_alter_contest_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Further description of the contest, such as rules and conditions'),
        ),
    ]
